@HostAddress = http://localhost:5000
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTczNDc3OTQ1OH1dLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwiYXVkIjoiYXV0aGVudGljYXRlZCIsImVtYWlsIjoic3V2cmF0MjlAZ21haWwuY29tIiwiZXhwIjoxNzM0NzgzMDU4LCJpYXQiOjE3MzQ3Nzk0NTgsImlzX2Fub255bW91cyI6ZmFsc2UsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9hdXRoL3YxIiwicGhvbmUiOiIiLCJyb2xlIjoiYXV0aGVudGljYXRlZCIsInNlc3Npb25faWQiOiI2OTI4NTMzMi0yMGNkLTRhN2EtYWQyYi01ODlmZDY5ZjQ0MGUiLCJzdWIiOiJmMmU4MDJkNS04NzgyLTQzZjctODdmZC05OWQwMTQyMDZjNzIiLCJ1c2VyX21ldGFkYXRhIjp7ImFkbWluIjp0cnVlfX0.zSaa9GZjCeauWbF2xiVN-5CuLhRInlL-nPSP2Rk81gQ

GET {{HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{AccessToken}}

###
